include:
  - docker-compose-mara.yaml
services:
  workspace-api:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/workspace-api:latest
    # container_name: workspace-api
    environment:
      - VIRTUAL_HOST=workspace-api.local
      - VIRTUAL_PORT=8002
    networks:
      - nanome-ai-network
    ports:
      - 8002
    volumes:
      - workspace-api-volume:/data

  workspace-load-service:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/workspace-load-service:latest
    # container_name: workspace-load-service
    environment:
      - VIRTUAL_HOST=workspace-load-service.local
      - VIRTUAL_PORT=8003
    networks:
      - nanome-ai-network
    ports:
      - 8003

volumes:
  workspace-api-volume:
