services:
  mara-ai:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/mara-enterprise:latest
    # container_name: mara-ai
    environment:
      - VIRTUAL_HOST=mara-ai.local
      - TOOL_SERVER_URL=http://mara-tool-server:8001
    env_file: .env.maraserver
    depends_on:
      - mara-tool-server
    networks:
      - nanome-ai-network
    volumes:
      - mara-ai-volume:/app/data
    ports:
      - 8000

  mara-tool-server:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/mara-tool-server-enterprise:latest
    # container_name: mara-tool-server
    environment:
      - VIRTUAL_HOST=mara-tool-server.local
    env_file: .env.toolserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mara-tool-volume:/data
    networks:
      - nanome-ai-network
    ports:
      - 8001

  workspace-api:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/workspace-api:latest
    # container_name: workspace-api
    environment:
      - VIRTUAL_HOST=workspace-api.local
    networks:
      - nanome-ai-network
    ports:
      - 8002
    volumes:
      - workspace-api-volume:/data

  workspace-load-service:
    image: 441665557124.dkr.ecr.us-west-1.amazonaws.com/workspace-load-service:latest
    # container_name: workspace-load-service
    environment:
      - VIRTUAL_HOST=workspace-load-service.local
    networks:
      - nanome-ai-network
    ports:
      - 8003

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # Required for nginx-proxy to access container metadata
    networks:
      - nanome-ai-network

networks:
  nanome-ai-network:
    driver: bridge

volumes:
  mara-tool-volume:
  mara-ai-volume:
  workspace-api-volume:
