---
- name: Deploy Mara Tool Server
  hosts: tool-servers
  tasks:
    - set_fact:
        working_dir: "/home/{{ ansible_user }}/tool-server"

    - name: Create working directory
      command: mkdir -p "{{ working_dir }}"
  
    - set_fact:
        https_enabled: "{{ https_enabled | default(false) }}"

    - set_fact:
        port: "{{ 443 if https_enabled else 8001 }}"

    - set_fact:
        host_certs_path: "{{working_dir}}/certs/"
    
    - set_fact:
        host_env_file: "{{working_dir}}/.env"

    - name: create host_certs_path if not already exists
      command: mkdir -p "{{ host_certs_path }}"

    - name: Log in to AWS ECR
      shell: |
        aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 441665557124.dkr.ecr.us-west-1.amazonaws.com
      register: login_output

    - name: Pull the latest image from ECR
      docker_image:
        name: 441665557124.dkr.ecr.us-west-1.amazonaws.com/mara-tool-server-enterprise
        tag: latest
        source: pull

    - name: Tag image with simpler name
      shell: docker tag 441665557124.dkr.ecr.us-west-1.amazonaws.com/mara-tool-server-enterprise:latest mara-tool-server-enterprise:latest
      register: tag_output

    - name: Copy the certs path to the remote server
      when: certs_path is defined and https_enabled
      copy:
        src: "{{ certs_path }}"
        dest: "{{ host_certs_path }}"
    - name: Copy .env file to the remote server
      when: env_file is defined
      copy:
        src: "{{ env_file }}"
        dest: "{{ host_env_file }}"

    - name: Check if Docker container exists
      community.docker.docker_container_info:
        name: mara-tool-server
      register: container_info
      failed_when: false  # Prevents failure if the container does not exist

    - name: Stop existing Docker container.
      docker_container:
        name: mara-tool-server
        state: stopped
      when: container_info.exists is defined and container_info.exists
    
    - name: Remove any existing Docker container with same name
      docker_container:
        name: mara-tool-server
        state: absent
      when: container_info.exists is defined and container_info.exists

    - name: Run the Docker container
      docker_container:
        name: mara-tool-server
        image: mara-tool-server-enterprise:latest
        state: started
        restart_policy: always
        platform: linux/amd64
        ports:
          - "{{ port }}:8001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{ host_certs_path }}:/app/certs/"
          - mara-tool-volume:/data
        env:
          HTTPS: "{{ https_enabled | string }}"
        env_file: "{{ host_env_file }}"
    - name: Assert Docker container running
      shell: docker ps | grep mara-tool-server
      register: container_status
      failed_when: container_status.rc != 0
      changed_when: container_status.rc == 0
      ignore_errors: false
