- name: Install AWSCLI on Windows
  hosts: windows
  tasks:
    - name: Download AWSCLI Install script
      ansible.windows.win_shell: |
        msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi
      args:
        executable: powershell

    - name: Verify AWSCLI installation
      ansible.windows.win_shell: |
        aws --version
      args:
        executable: cmd
      register: aws_version

    - name: Debug AWSCLI version
      ansible.builtin.debug:
        msg: "AWSCLI installed successfully: {{ aws_version.stdout }}"