---
- name: Download and Install Photon
  hosts: windows
  gather_facts: no
  vars:
    photon_s3: s3://nanome/enterprise_deployment/Photon-OnPremise-Server-SDK_v4-0-29-11263.zip
    license_s3: https://nanome.s3.us-west-1.amazonaws.com/enterprise_deployment/simim91296%40gocasin.com.Photon-vX.free.100-ccu.license 
    photon_zip_dir: C:\Users\Administrator\Desktop\photon.zip
    photon_dir: C:\Users\Administrator\Desktop\photon
    license_file: 'C:\Users\Administrator\Desktop\photon\deploy\bin_Win64\photon.license'
  tasks:
    - name: Check if the photon zip file exists on the remote server
      win_stat:
        path: "{{ photon_zip_dir }}"
      register: photon_zip_exists
    - name: Download Photon from S3 bucket
      when: not photon_zip_exists.stat.exists
      win_command: aws s3 cp {{ photon_s3 }} {{ photon_zip_dir }}
    - name: Unzip the file
      when: not photon_zip_exists.stat.exists
      win_unzip:
        src: "{{ photon_zip_dir }}"
        dest: "{{ photon_dir }}"
      register: unzip_result
    - name: Start the Photon Service
      win_shell: |
        cd C:\Users\Administrator\Desktop\photon\Photon-OnPremise-Server-SDK_v4-0-29-11263\deploy\bin_Win64
        ./_service.install.cmd
        ./_service.start.cmd
      register: lb_service_start
