- name: Install Docker on Windows
  hosts: windows
  tasks:
    - name: Run Docker Install script
      ansible.windows.win_shell: |
        Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
        .\install-docker-ce.ps1
      args:
        executable: powershell

    - name: Verify Docker installation
      ansible.windows.win_shell: |
        docker --version
      args:
        executable: cmd
      register: docker_version

    - name: Debug Docker version
      ansible.builtin.debug:
        msg: "Docker installed successfully: {{ docker_version.stdout }}"
