---
- name: Retrieve LLM_LLM_API_KEY from .env file
  hosts: mara-servers
  tasks:
    - set_fact:
        env_file_path: "/home/{{ansible_user}}/mara/.env"
    - name: Check if .env file exists
      stat:
        path: "{{ env_file_path }}"
      register: env_file_stat

    - name: Fail if .env file is not found
      fail:
        msg: ".env file not found on the remote server"
      when: not env_file_stat.stat.exists

    - name: Retrieve LLM_API_KEY from .env file
      shell: "grep '^LLM_API_KEY=' {{ env_file_path }} | cut -d '=' -f2-"
      register: llm_api_key_value
      when: env_file_stat.stat.exists

    # Write llm_api_key to a local file
    - name: Write LLM_API_KEY to a local file
      copy:
        content: "{{ llm_api_key_value.stdout }}"
        dest: "{{ llm_api_key_txt }}"
      delegate_to: localhost
      when: llm_api_key_value.stdout is defined
