---
- name: Retrieve AWS credentials from tool server
  hosts: tool-servers
  tasks:
    - set_fact:
        credentials_file_path: "/home/{{ansible_user}}/.aws/credentials"
    - name: Check if credentials file exists
      stat:
        path: "{{ credentials_file_path }}"
      register: aws_credentials_file_stat

    - name: Exit playbook if aws credentials file is not found
      meta: end_play
      when: not aws_credentials_file_stat.stat.exists

    - name: Retrieve AWS_ACCESS_KEY_ID from credentials file
      shell: "grep 'aws_access_key_id' /home/{{ ansible_user }}/.aws/credentials | awk '{print $3}'"
      register: aws_access_key_id
      when: aws_credentials_file_stat.stat.exists
    
    - name: Retrieve AWS_SECRET_ACCESS_KEY from credentials file
      shell: "grep 'aws_secret_access_key' /home/{{ ansible_user }}/.aws/credentials | awk '{print $3}'"
      register: aws_secret_access_key
      when: aws_credentials_file_stat.stat.exists

    # Write creds to a local file
    - name: Write credentials to a local file
      copy:
        content: "aws_access_key: {{ aws_access_key_id.stdout }}\naws_secret_key: {{ aws_secret_access_key.stdout }}"
        dest: "{{ output_yaml }}"
      delegate_to: localhost
      when: aws_secret_access_key.stdout is defined
